# Generated by Django 3.2.4 on 2021-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rates_number', models.IntegerField(default=0)),
                ('rates_total', models.IntegerField(default=0)),
            ],
        ),
    ]
